update test
royashcenazi/parsigs pull request #15
Opened 2023-07-23 08:55 UTC by micies

2023-07-24 12:07 UTC, royashcenazi requested changes

2023-07-24 12:07 UTC, royashcenazi commented on parsigs/parse_sig_api.py
> +
@micies great work with Hypothesis! 
remove the old changes and rebase master as there were changes

2023-07-24 12:10 UTC, micies commented
ok

2023-07-24 12:17 UTC, micies commented
i'm change it

2023-07-26 07:08 UTC, royashcenazi commented on tests/test_parsig_api.py
> +        sig = "קח שתי טבליות איבופרופן 3 פעמים בכל שבוע"
this needs to be deleted :)

2023-07-26 07:09 UTC, royashcenazi commented on tests/test_hypothesis.py
> +        sig = f"Take 1 tablet of ibuprofen {integer}mg 3 times every day for 10 weeks"
rename this file to test_propery_parsig_api (the `test_` starter is for `pytest` to run this script when testing the project)

2023-07-26 07:31 UTC, royashcenazi commented on tests/test_propery_parsig_api.py
> +    def test_parse_sig_strength(self, integer):
rename integer => strength

2023-07-26 07:43 UTC, merged